const modifierData = [
        { name: "Thick-Skinned", multiplier: 1.1, description: "Monsters have +1 AC." },
        { name: "Vicious", multiplier: 1.1, description: "Monsters deal 1 extra point of damage on all attacks." },
        { name: "Tenacious", multiplier: 1.1, description: "Monsters have 10% more hit points." },
        { name: "Sure-Footed", multiplier: 1.1, description: "Monsters have advantage on saves against being knocked prone." },
        { name: "Keen-Eyed", multiplier: 1.1, description: "Monsters have advantage on Perception checks." },
        { name: "Frenzied", multiplier: 1.15, description: "Monsters have advantage on their first attack roll in combat." },
        { name: "Toughened", multiplier: 1.15, description: "Monsters are resistant to poison damage." },
        { name: "Chilling Aura", multiplier: 1.15, description: "The area around the monsters is unnaturally cold, disadvantage on checks to resist cold effects." },
        { name: "Pack Tactics", multiplier: 1.2, description: "Advantage on attacks when an ally is within 5ft of the target." },
        { name: "Arcane-Infused", multiplier: 1.2, description: "Attacks are magical." },
        { name: "Fast Healing", multiplier: 1.2, description: "Monsters regenerate 1 hit point at the start of their turn." },
        { name: "Slippery", multiplier: 1.2, description: "Monsters have advantage on saves to escape grapples or restraints." },
        { name: "Hulking", multiplier: 1.2, description: "Monsters are one size category larger." },
        { name: "Bloodthirsty", multiplier: 1.25, description: "Deal an extra die of damage against creatures below half health." },
        { name: "Resilient", multiplier: 1.25, description: "Monsters have proficiency in one additional saving throw." },
        { name: "Shielded", multiplier: 1.25, description: "Monsters begin combat with temporary hit points equal to 10% of their maximum." },
        { name: "Ambusher", multiplier: 1.25, description: "Monsters have advantage on attack rolls against any creature they have surprised." },
        { name: "Caustic Blood", multiplier: 1.3, description: "Melee attackers take 1d4 acid damage." },
        { name: "Spell-Resistant", multiplier: 1.3, description: "Advantage on saving throws against spells." },
        { name: "Unrelenting", multiplier: 1.3, description: "If the monster is reduced to 0 HP, it makes one final melee attack before dying." },
        { name: "Fearsome", multiplier: 1.3, description: "Creatures starting their turn near the monster must save or become frightened." },
        { name: "Vampiric Touch", multiplier: 1.35, description: "Monsters heal for half the damage they deal once per combat." },
        { name: "Explosive Demise", multiplier: 1.35, description: "When a monster dies, it explodes in a burst of elemental energy (fire, cold, etc.)." },
        { name: "Paralyzing Strike", multiplier: 1.4, description: "Once per combat, an attack can force a save against paralysis." },
        { name: "Phase-Touched", multiplier: 1.4, description: "Monsters can briefly become ethereal, ignoring difficult terrain and moving through objects." },
        { name: "Reflective Carapace", multiplier: 1.4, description: "Chance to reflect single-target spells." },
        { name: "Splitter", multiplier: 1.45, description: "When a monster is brought below half health, it splits into two smaller versions with half the remaining HP." },
        { name: "Gravity Well", multiplier: 1.45, description: "The area around the monsters is high gravity, costing double movement." },
        { name: "Multi-Attack", multiplier: 1.5, description: "Gain one additional attack with their primary weapon." },
        { name: "Elemental Adept", multiplier: 1.5, description: "Monsters can change their damage type to an element of their choice (fire, cold, lightning)." },
        { name: "Regenerating", multiplier: 1.5, description: "Regenerate 10% of max HP at the start of their turn." },
        { name: "Antimagic Cone", multiplier: 1.5, description: "One monster projects a cone of antimagic, nullifying spells within it." },
        { name: "Teleporting", multiplier: 1.5, description: "Monsters can teleport a short distance as a bonus action." },
        { name: "Charmed", multiplier: 1.5, description: "Monsters are immune to the charmed condition." },
        { name: "Cunning Action", multiplier: 1.5, description: "Monsters can take a bonus action on each of their turns to Dash, Disengage, or Hide." },
        { name: "Evasive", multiplier: 1.6, description: "Take half damage on failed Dex saves, and no damage on success." },
        { name: "Legendary Resistance (1/Day)", multiplier: 1.6, description: "If the monster fails a saving throw, it can choose to succeed instead (1/Day)." },
        { name: "Stunning Gaze", multiplier: 1.6, description: "As an action, the monster can force a creature that can see it to save or be stunned." },
        { name: "Swarm Tactics", multiplier: 1.6, description: "The monsters act as a single swarm, sharing a turn and gaining resistance to physical damage." },
        { name: "Soul Drain", multiplier: 1.65, description: "Attacks reduce the target's maximum HP until a long rest." },
        { name: "Corrosive", multiplier: 1.65, description: "The monster's attacks damage armor and weapons, reducing their effectiveness." },
        { name: "Hive Mind", multiplier: 1.7, description: "All monsters are telepathically linked." },
        { name: "Time-Warped", multiplier: 1.7, description: "Monsters are occasionally affected by a haste or slow spell at random." },
        { name: "Mirage", multiplier: 1.75, description: "Surrounded by illusory duplicates (mirror image)." },
        { name: "Petrifying Touch", multiplier: 1.75, description: "A monster's attack can force a save against being turned to stone." },
        { name: "Aura of Weakness", multiplier: 1.75, description: "Creatures near the monster have disadvantage on Strength-based checks and saves." },
        { name: "Life Leech", multiplier: 1.8, description: "A damaging aura surrounds the monsters, draining life from all nearby creatures." },
        { name: "Spell-Siphon", multiplier: 1.8, description: "When a creature casts a spell near the monster, the monster can use its reaction to gain temporary HP." },
        { name: "Reactive", multiplier: 1.8, description: "Can take one reaction on every turn in a combat." },
        { name: "Adaptive Resistance", multiplier: 1.85, description: "Gains resistance to the first type of damage it takes." },
        { name: "Ethereal Jaunt", multiplier: 1.85, description: "The monster can shift between the Ethereal Plane and the Material Plane as a bonus action." },
        { name: "Incorporeal", multiplier: 1.9, description: "Resistant to non-magical physical damage and can move through objects." },
        { name: "Aura of Silence", multiplier: 1.9, description: "No sound can be created within or pass through a 20-foot radius of the monster." },
        { name: "Magic Immunity", multiplier: 1.9, description: "The monster is immune to spells of 3rd level or lower." },
        { name: "Annihilating Strike", multiplier: 1.95, description: "Once per combat, an attack can cause a target to be unable to be revived by normal means if it kills them." },
        { name: "Mythic Trait", multiplier: 2.0, description: "When reduced to 0 HP, regains full health and gains a new ability." },
        { name: "True Sight", multiplier: 2.0, description: "The monster has true sight out to 120 feet, seeing through illusions and invisibility." },
        { name: "Unstoppable", multiplier: 2.0, description: "The monster is immune to being stunned, paralyzed, or petrified." },
        { name: "Void-Touched", multiplier: 2.0, description: "The monster is resistant to all damage except force and psychic." },
        { name: "Legendary Actions", multiplier: 2.0, description: "Gains 1 legendary action per round." },
        { name: "Aura of Madness", multiplier: 2.1, description: "Creatures nearby must save or suffer from short-term madness." },
        { name: "Chronomancer", multiplier: 2.1, description: "The monster can force a creature to re-roll an attack roll, ability check, or saving throw." },
        { name: "Spell-Thief", multiplier: 2.2, description: "The monster can 'steal' a spell from a caster, preventing them from using it and allowing the monster to cast it once." },
        { name: "Planar Instability", multiplier: 2.2, description: "The arena randomly shifts to a different plane of existence for one round." },
        { name: "Symbiotic", multiplier: 2.25, description: "Two different types of monsters are chosen, and they fight as a single symbiotic entity, sharing abilities." },
        { name: "Damage Transfer", multiplier: 2.25, description: "The monsters can transfer damage they take to a designated 'champion' monster." },
        { name: "Summoner", multiplier: 2.3, description: "Can summon lesser creatures to aid it in battle." },
        { name: "Possessing", multiplier: 2.3, description: "If a player is killed, the monster's spirit possesses their body, forcing them to fight their allies." },
        { name: "Aura of Antimagic", multiplier: 2.4, description: "All magic is suppressed in a 30-foot radius." },
        { name: "Reality Warper", multiplier: 2.4, description: "The monster can change the terrain of the arena as a legendary action." },
        { name: "Legendary Resistance (2/Day)", multiplier: 2.5, description: "Can choose to succeed a failed saving throw (2/Day)." },
        { name: "God-Slayer", multiplier: 2.5, description: "The monster deals double damage to creatures of a celestial or fiendish nature." },
        { name: "Perfect Camouflage", multiplier: 2.5, description: "The monster is permanently invisible." },
        { name: "Temporal Clone", multiplier: 2.6, description: "The monster summons a version of itself from one round in the future to fight alongside it." },
        { name: "Eldritch Storm", multiplier: 2.6, description: "The arena is wracked by a magical storm that deals random elemental damage each round." },
        { name: "Reactive Evolution", multiplier: 2.7, description: "Every round, the monster adapts to the party's tactics, gaining a new resistance or ability." },
        { name: "Aura of Nullification", multiplier: 2.7, description: "Creatures near the monster cannot heal or regenerate." },
        { name: "Action-Oriented", multiplier: 2.75, description: "Has special 'villain actions' that trigger at different initiative counts." },
        { name: "Avatar of a God", multiplier: 2.8, description: "The monster is a direct avatar of a deity, granting it divine power and immunities." },
        { name: "World-Breaker", multiplier: 2.8, description: "The monster's attacks sunder the ground, creating difficult terrain and chasms." },
        { name: "Soul Eater", multiplier: 2.9, description: "A creature killed by the monster has its soul consumed and cannot be resurrected by any means short of a wish spell." },
        { name: "Legendary Actions (2/Day)", multiplier: 3.0, description: "Gains 2 legendary actions per round." },
        { name: "Immunity", multiplier: 3.0, description: "The monster is immune to one common damage type (e.g., fire, slashing)." },
        { name: "Unraveling Form", multiplier: 3.0, description: "The monster's form is unstable. Each time it is hit, it might teleport, turn invisible, or unleash a burst of energy." },
        { name: "Echoes of the Past", multiplier: 3.2, description: "The monster summons spectral echoes of previously defeated players to fight for it." },
        { name: "Primordial", multiplier: 3.2, description: "The monster is a being of pure creation or destruction, its attacks ignore all resistances." },
        { name: "Spell-Eater", multiplier: 3.5, description: "Immune to magic and heals from spells cast upon it." },
        { name: "Apocalyptic Aura", multiplier: 3.5, description: "The monster's aura deals continuous, untyped damage to all creatures within 60 feet." },
        { name: "King of Monsters", multiplier: 3.75, description: "If multiple monsters are present, one is a 'King' with double HP, legendary actions, and the ability to command the others." },
        { name: "Aspect of the Tarrasque", multiplier: 4.0, description: "Reflective carapace, immune to non-magical weapons, 3 legendary resistances." },
        { name: "Legendary Actions (3/Day)", multiplier: 4.0, description: "Gains 3 legendary actions per round." },
        { name: "Time Lord", multiplier: 4.0, description: "The monster can take two full turns in a single round." },
        { name: "Wish-Twister", multiplier: 4.2, description: "The monster can cast counterspell at will and can twist the effects of beneficial spells into harmful ones." },
        { name: "Unkillable", multiplier: 4.5, description: "Cannot be reduced below 1 HP unless a specific, hidden condition is met." },
        { name: "Planar Collapse", multiplier: 4.5, description: "The monster is a living gateway to another plane. Random creatures from that plane are pulled through into the fight each round." },
        { name: "Anti-Divinity", multiplier: 4.75, description: "The monster's presence severs the connection to the gods. Divine casters (Clerics, Paladins) cannot cast spells." },
        { name: "True Form", multiplier: 5.0, description: "When defeated, reveals its true, much more powerful form and the fight begins anew." },
        { name: "All-Resistant", multiplier: 5.0, description: "The monster is resistant to all damage types." },
        { name: "The Final Boss", multiplier: 6.0, description: "Has Mythic Actions, 3 Legendary Actions, and Legendary Resistance (3/Day)." },
        { name: "Player Nemesis", multiplier: 7.0, description: "Has abilities, spells, and tactics designed to counter the party." }
    ].sort((a, b) => a.multiplier - b.multiplier);